name: Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} add-on
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data \
            --image "sengled-local-server-{arch}" \
            --docker-hub "ghcr.io/${{ github.repository_owner }}" \
            --addon
