name: Build Home Assistant Add-on

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build Add-on
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [aarch64, armhf, armv7, amd64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master

      - name: Check if add-on should be built
        id: check
        run: |
          if [[ "${{ steps.info.outputs.changed_files }}" =~ (requirements.txt|Dockerfile|build.yaml|config.yaml|rootfs/) ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "release" ]]; then
            echo "build=true" >> $GITHUB_OUTPUT
          else
            echo "build=false" >> $GITHUB_OUTPUT
          fi

      - name: Login to GitHub Container Registry
        if: steps.check.outputs.build == 'true' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Add-on
        if: steps.check.outputs.build == 'true'
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }}
            --target .
            --image "sengled-local-server-{arch}"
            --docker-hub ${{ env.REGISTRY }}/${{ github.repository_owner }}
            --addon