name: Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  init:
    runs-on: ubuntu-latest
    name: Initialize builds
    outputs:
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Find add-on directories
        id: changed_addons
        run: |
          declare -a addons
          addons+=(".")  # This add-on is in the root directory
          changed=$(echo '${{ steps.changed_files.outputs.all }}' | jq -R 'split(" ")' | jq -r '.[]')
          if [[ -n "${changed}" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "addons=$(echo ${addons[@]} | jq -R -s 'split(" ")')" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} add-on
    needs: init
    if: needs.init.outputs.changed == 'true'
    strategy:
      matrix:
        addon: ${{ fromJson(needs.init.outputs.changed_addons) }}
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.addon }} add-on
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{ matrix.addon }} \
            --addon
